# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 919bcd643a4ef390530f976639f4448a48a8f472f026b10091e72fe9a6e5183d5d7946c2adec0f69dc4a3111cd6702626972858ebc3ac52641786df90e4a5c0b

test:
  secret_key_base: 0a1a48140cc2c33b54d4769875aa7a7a9b72bcc7f3e6a6c7d6c1b3aa52cd2411fbddf05640cb3b343adedd26136b35dd5be4ac7cc2c96d804740e10cd5ec8cc9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
